# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default="Roman's Blog", max_length=256, verbose_name='Site Name')),
                ('site_tagline', models.CharField(blank=True, max_length=256, verbose_name='Site Tagline')),
                ('featured_image', filebrowser.fields.FileBrowseField(blank=True, max_length=1024, verbose_name='Featured Image')),
                ('disqus_shortname', models.CharField(blank=True, max_length=64, verbose_name='Disqus Shortname')),
                ('google_analytics_id', models.CharField(blank=True, max_length=64, verbose_name='Google Analytics ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
