# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nDisallow: /admin\nDisallow: /search', verbose_name='robots.txt'),
        ),
    ]
