"""
Django settings for romans_blog project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
from importlib import import_module

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fvh+o&w4qo-afc#fu8fy7=1_imte!d7k1d)9q+=603@963+sk!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'filebrowser',
    'tinymce',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'pages',
    'cerulean_skin',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'romans_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'romans_blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files (user images, videos, other files)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# TinyMCE settings

TINYMCE_DEFAULT_CONFIG = {'theme': 'advanced',
                          'mode': 'textareas',
                          'width': 800,
                          'height': 600,
                          'plugins': 'preview,table',
                          'theme_advanced_buttons1': 'bold,italic,underline,strikethrough,|,'
                                                     'justifyleft,justifycenter,justifyright,justifyfull,|,'
                                                     'bullist,numlist,|,outdent,indent,|,forecolor,backcolor,|,'
                                                     'sup,sub,|,hr,|,blockquote,|,help',
                          'theme_advanced_buttons2': 'fontselect,fontsizeselect,formatselect,|,link,unlink,anchor,|,'
                                                     'image,|,removeformat,cleanup,|,code,preview',
                          'theme_advanced_buttons3': 'undo,redo,|,tablecontrols',
                          'browser_spellcheck': True,
                          'plugin_preview_width': 800,
                          'plugin_preview_height': 600,
                          'theme_advanced_font_sizes': '8pt,10pt,12pxt,14pxt,16pt,18pt,24pt,36pt,48pt',
                          'relative_urls': False,
                          }

# Skin settings

CURRENT_SKIN = 'cerulean_skin'
TINYMCE_DEFAULT_CONFIG['plugin_preview_pageurl'] = '/tinymce-preview/{0}/'.format(CURRENT_SKIN)
skin_settings = import_module('{0}.settings'.format(CURRENT_SKIN))
try:
    table_styles = skin_settings.TABLE_STYLES
    table_row_styles = skin_settings.TABLE_ROW_STYLES
except AttributeError:
    table_styles = table_row_styles = ''
TINYMCE_DEFAULT_CONFIG['table_styles'] = table_styles
TINYMCE_DEFAULT_CONFIG['table_row_styles'] = table_row_styles

# Load production settings if any
try:
    from .local_settings import *
except ImportError:
    pass
