# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160126_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulink',
            options={'ordering': ('position',), 'verbose_name': 'Menu Link', 'verbose_name_plural': 'Menu Links'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('title',), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='menulink',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
    ]
