# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 18:55
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170920_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='featured_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=1024, verbose_name='Featured Image'),
        ),
    ]
