# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160126_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_published', '-pk'), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
